const contactData = [
    {
      id: 1,
      name: "John Doe",
      phone_no: "123-456-7890",
      email_id: "john@example.com",
      message: "Hello, I'm interested in your services.",
    },
    {
      id: 2,
      name: "Jane Smith",
      phone_no: "987-654-3210",
      email_id: "jane@example.com",
      message: "Hi, I have a question about your products.",
    },
    {
      id: 3,
      name: "Alice Johnson",
      phone_no: "555-123-4567",
      email_id: "alice@example.com",
      message: "Greetings! I'd like to inquire about pricing.",
    },
    {
      id: 4,
      name: "Bob Williams",
      phone_no: "222-555-8888",
      email_id: "bob@example.com",
      message: "Good day! I need assistance with a purchase.",
    },
    {
      id: 5,
      name: "Emily Davis",
      phone_no: "333-777-9999",
      email_id: "emily@example.com",
      message: "Hello team! Can you provide more information?",
    },
    {
      id: 6,
      name: "Michael Brown",
      phone_no: "444-666-2222",
      email_id: "michael@example.com",
      message: "Hi there! I'm having trouble with the website.",
    },
    {
      id: 7,
      name: "Olivia Miller",
      phone_no: "666-999-1111",
      email_id: "olivia@example.com",
      message: "Greetings! I'd like to schedule a consultation.",
    },
    {
      id: 8,
      name: "William Wilson",
      phone_no: "777-333-4444",
      email_id: "william@example.com",
      message: "Hello! I'm interested in your latest offerings.",
    },
    {
      id: 9,
      name: "Sophia Taylor",
      phone_no: "888-222-5555",
      email_id: "sophia@example.com",
      message: "Hi! Can someone assist me with technical support?",
    },
    {
      id: 10,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 11,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 12,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 13,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 14,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 15,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 16,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 17,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 18,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
    {
      id: 19,
      name: "James Lee",
      phone_no: "999-111-7777",
      email_id: "james@example.com",
      message: "Good day! I need help with a billing issue.",
    },
  ];
  
  export default contactData;